### ISSUE TITLE
Self-signed certificate support

### ISSUE THREAD

**Issue by EricCrosson** [filipre/hubot-available#3]
Hello,

sweet package!  Very helpful :)

I may have missed something in the documentation, but is there support for monitoring hosts over https with self-signed certs?  If so, what's the procedure to get it working?

Thanks for publishing this, and
Happy hacking

**Comment by filipre** [comment]
Hey,
thanks for your kind words!

Currently I don't support self-signed certs. However, maybe you can implement it yourself: The [script](https://github.com/filipre/hubot-available/blob/master/src/available.coffee#L167) only makes a simple GET request using Hubot's http method described [here](https://github.com/github/hubot/blob/master/docs/scripting.md#making-http-calls). On first sight I couldn't see how to inject certs, though. 

Now that I think of it, I remember doing something similar to our internal Hubot instance *on Hubot's startup* (instead of in each possible package). I will take a look what we did and let you know!

Cheers

**Comment by EricCrosson** [comment]
Thanks for the pointers, I'd be happy to take a look. That solution involving priming the certs on startup sounds very preferable! Can't wait to see what turns up

**Comment by filipre** [comment]
So: We also had the problem that Hubot was behind a corporate proxy and Hubot didn't support this (not sure if they do it now).

We replaced the `index.coffee` (which was created by npm) with some additional code:

```coffeescript
#Initialize Proxy
GlobalTunnel = require 'global-tunnel'
GlobalTunnel.initialize
    host: '<your corporate proxy>'
    port: <corporate proxy port>

#Initialize Certs
ssl_root_cas = require 'ssl-root-cas'
path = require 'path'
ssl_root_cas.inject()
    .addFile(path.join(__dirname, '..', '..', 'certs', '<pem file>.pem'))
    .addFile(path.join(__dirname, '..', '..', 'certs', '<pem file>.pem'))
    .addFile(path.join(__dirname, '..', '..', 'certs', '<crt file>.crt'))
    .addFile path.join(__dirname, '..', '..', 'certs', '<crt file>.crt')

#the rest is hubot's original code
```

I hope this helps!

**Comment by EricCrosson** [comment]
This definitely works. Nice approach!

I would love for this solution to be documented somewhere, so others in our position can benefit from your work. However, inside this repository does not seem to be the best place ;) so I'll close the issue now.

Cheers 🍻 and thank you once again
